name: Build Linux/macOS Binaries

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-all:
    name: Build for ${{ matrix.runtime }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - linux-x64
          - linux-musl-x64
          - linux-musl-arm64
          - linux-arm
          - linux-arm64
          - osx-x64
          - osx-arm64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish ${{ matrix.runtime }} Binary
        run: >
          dotnet publish ssh-c.csproj
          -c Release
          -r ${{ matrix.runtime }}
          --self-contained true
          -p:PublishSingleFile=true
          -p:PublishTrimmed=true
          -p:EnableCompressionInSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -o publish/${{ matrix.runtime }}

      - name: Rename published binary to ssh-c
        run: |
          mv publish/${{ matrix.runtime }}/com.repasscloud.ssh-c publish/${{ matrix.runtime }}/ssh-c

      - name: Make binary executable
        run: chmod +x publish/${{ matrix.runtime }}/ssh-c

      - name: Verify binary format
        run: file publish/${{ matrix.runtime }}/ssh-c

      - name: Generate SHA256 checksum
        run: sha256sum publish/${{ matrix.runtime }}/ssh-c > publish/${{ matrix.runtime }}/ssh-c_${{ matrix.runtime }}.sha256

      - name: Zip binary and checksum
        run: |
          cd publish/${{ matrix.runtime }}
          zip ssh-c_${{ matrix.runtime }}.zip ssh-c ssh-c_${{ matrix.runtime }}.sha256

      - name: Upload Zipped Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssh-c-${{ matrix.runtime }}-unsigned
          path: publish/${{ matrix.runtime }}/ssh-c_${{ matrix.runtime }}.zip
