name: Build & Release ssh-c

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-linux-windows:
    name: Build Release Assets (Linux + Windows)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [win-x64, linux-x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish (${{ matrix.runtime }})
        run: |
          dotnet publish ssh-c.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:EnableCompressionInSingleFile=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o publish/${{ matrix.runtime }}

      - name: Archive binary
        run: |
          cd publish/${{ matrix.runtime }}
          zip ssh-c-${{ matrix.runtime }}.zip ssh-c*
          sha256sum ssh-c-${{ matrix.runtime }}.zip > ssh-c-${{ matrix.runtime }}.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            publish/${{ matrix.runtime }}/ssh-c-${{ matrix.runtime }}.zip
            publish/${{ matrix.runtime }}/ssh-c-${{ matrix.runtime }}.sha256

  release-macos:
    name: Build Release Assets (macOS)
    runs-on: macos-latest

    strategy:
      matrix:
        runtime: [osx-x64, osx-arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish (${{ matrix.runtime }})
        run: |
          dotnet publish ssh-c.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:EnableCompressionInSingleFile=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o publish/${{ matrix.runtime }}

      - name: Archive binary
        run: |
          cd publish/${{ matrix.runtime }}
          zip ssh-c-${{ matrix.runtime }}.zip ssh-c
          shasum -a 256 ssh-c-${{ matrix.runtime }}.zip > ssh-c-${{ matrix.runtime }}.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            publish/${{ matrix.runtime }}/ssh-c-${{ matrix.runtime }}.zip
            publish/${{ matrix.runtime }}/ssh-c-${{ matrix.runtime }}.sha256

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload changelog
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}


  # scoop:
  #   name: Scoop manifest push
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Update scoop manifest (TODO)
  #       run: echo "Add your scoop manifest updater here"

  # homebrew:
  #   name: Homebrew formula push
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Update Homebrew formula (TODO)
  #       run: echo "Add your homebrew formula updater here"

  # aur:
  #   name: AUR PKGBUILD push
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Update AUR PKGBUILD (TODO)
  #       run: echo "Add your AUR updater here"
